const products=[
{id:1,name:'Mobile Legends Diamond',cat:'topup',price:3000,img:'https://upload.wikimedia.org/wikipedia/en/9/93/Mobile_Legends_Logo.png',fallback:'ML',badge:'BEST SELLER',sold:1280,rating:'4.9'},
{id:2,name:'Free Fire Diamond',cat:'topup',price:5000,img:'https://upload.wikimedia.org/wikipedia/en/c/c5/Logo_of_Garena_Free_Fire.png',fallback:'FF',badge:'HOT',sold:980,rating:'4.8'},
{id:3,name:'Joki Rank ML',cat:'joki',price:10000,img:'https://upload.wikimedia.org/wikipedia/en/9/93/Mobile_Legends_Logo.png',fallback:'JR',badge:'PROMO',sold:520,rating:'4.9'},
{id:4,name:'YouTube Premium',cat:'premium',price:15000,img:'https://upload.wikimedia.org/wikipedia/commons/e/ef/Youtube_logo.png',fallback:'YT',badge:'READY',sold:760,rating:'4.8'},
{id:5,name:'Spotify Premium',cat:'premium',price:18000,img:'https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg',fallback:'SP',badge:'READY',sold:640,rating:'4.7'},
{id:6,name:'Akun Netflix',cat:'akun',price:25000,img:'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg',fallback:'NF',badge:'LIMITED',sold:430,rating:'4.8'},
{id:7,name:'OTP Virtual',cat:'lainnya',price:5000,img:'https://upload.wikimedia.org/wikipedia/commons/5/51/Key_icon.svg',fallback:'OTP',badge:'READY',sold:300,rating:'4.6'}
];
let cartItems=[];let activeCat='all';const ADMIN_WA='628161113164';
function rupiah(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)}function byId(id){return document.getElementById(id)}function cartTotal(){return cartItems.reduce((sum,item)=>sum+item.price,0)}
function logoHtml(p){return `<img src="${p.img}" alt="${p.name}" loading="lazy" onerror="this.outerHTML='<div class=\'photo-box\'>${p.fallback}</div>'">`}
function renderProducts(){const grid=byId('grid');const searchInput=byId('searchInput');if(!grid)return;const q=(searchInput?.value||'').toLowerCase().trim();const result=products.filter(p=>(activeCat==='all'||p.cat===activeCat)&&p.name.toLowerCase().includes(q));grid.innerHTML='';if(!result.length){grid.innerHTML='<div class="empty-state">Produk tidak ditemukan.</div>';return;}result.forEach(p=>{const div=document.createElement('div');div.className='card product-card';div.innerHTML=`<span class="product-badge">${p.badge}</span><div class="product-img"><div class="profile-box">${logoHtml(p)}</div></div><h3>${p.name}</h3><p class="product-desc">Produk digital siap order.</p><div class="product-meta"><span>⭐ ${p.rating}</span><span>Terjual ${p.sold}+</span></div><div class="price">${rupiah(p.price)}</div><button type="button" data-add="${p.id}">Beli</button>`;grid.appendChild(div);});}
function renderCart(){document.querySelectorAll('#cartCount').forEach(el=>el.textContent=cartItems.length);const qty=byId('cartQty');const total=byId('total');if(qty)qty.textContent=cartItems.length;if(total)total.textContent=rupiah(cartTotal());const box=byId('cartItems');if(!box)return;if(!cartItems.length){box.innerHTML='<div class="cart-empty">Keranjang masih kosong.</div>';return;}box.innerHTML=cartItems.map((item,i)=>`<div class="cart-item"><div><strong>${item.name}</strong><span>${rupiah(item.price)}</span></div><button type="button" data-remove="${i}">Hapus</button></div>`).join('');}
function showToast(text){const t=byId('liveToast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}function add(id){const p=products.find(x=>x.id===id);if(!p)return;cartItems.push(p);renderCart();showToast(`${p.name} masuk keranjang`)}function removeItem(i){cartItems.splice(i,1);renderCart()}function showOverlay(){const o=byId('overlay');if(o)o.style.display='block'}function hideOverlay(){const o=byId('overlay');if(o)o.style.display='none'}function openMenu(){byId('navPanel')?.classList.add('open');showOverlay()}function closePanels(){byId('navPanel')?.classList.remove('open');byId('cart')?.classList.remove('open');hideOverlay()}function openCart(){byId('navPanel')?.classList.remove('open');byId('cart')?.classList.add('open');showOverlay();renderCart()}function cleanWa(n){let s=(n||'').replace(/\D/g,'');if(s.startsWith('0'))s='62'+s.slice(1);return s}
function checkout(){const name=byId('buyerName')?.value.trim();const wa=cleanWa(byId('buyerWa')?.value);const pay=byId('paymentMethod')?.value;const note=byId('orderNote')?.value.trim();if(!cartItems.length){alert('Keranjang masih kosong.');return;}if(!name){alert('Nama pembeli wajib diisi.');return;}if(!wa){alert('Nomor handphone wajib diisi.');return;}if(!pay){alert('Pilih metode pembayaran.');return;}const items=cartItems.map((x,i)=>`${i+1}. ${x.name} - ${rupiah(x.price)}`).join('\n');const msg=`Halo Admin CORE RAMPAGE, saya ingin order.\n\nNama: ${name}\nNomor HP: ${wa}\nMetode Pembayaran: ${pay}\n\nProduk:\n${items}\n\nTotal: ${rupiah(cartTotal())}\nCatatan: ${note||'-'}\n\nTelegram Admin: @codestackdev\nWeChat: @codestackdev\n\nMohon diproses.`;window.open(`https://wa.me/${ADMIN_WA}?text=${encodeURIComponent(msg)}`,'_blank')}
function init(){byId('menuBtn')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openMenu()});byId('closeMenu')?.addEventListener('click',closePanels);byId('overlay')?.addEventListener('click',closePanels);byId('closeCart')?.addEventListener('click',closePanels);byId('cartBtn')?.addEventListener('click',e=>{e.preventDefault();openCart()});byId('categoryBtn')?.addEventListener('click',e=>{e.preventDefault();byId('tabs')?.classList.toggle('open')});byId('checkout')?.addEventListener('click',checkout);document.querySelectorAll('.nav-panel a').forEach(a=>a.addEventListener('click',closePanels));document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeCat=btn.dataset.cat;renderProducts();byId('tabs')?.classList.remove('open')}));byId('searchInput')?.addEventListener('input',renderProducts);document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]');if(addBtn)add(Number(addBtn.dataset.add));const rm=e.target.closest('[data-remove]');if(rm)removeItem(Number(rm.dataset.remove));});let slide=0;const slides=[...document.querySelectorAll('.banner')];const dots=[...document.querySelectorAll('.dot')];function showSlide(i){slides.forEach(s=>s.classList.remove('active'));dots.forEach(d=>d.classList.remove('active'));slide=i;slides[slide]?.classList.add('active');dots[slide]?.classList.add('active')}dots.forEach((d,i)=>d.addEventListener('click',()=>showSlide(i)));setInterval(()=>{if(slides.length)showSlide((slide+1)%slides.length)},4500);renderProducts();renderCart();}
document.addEventListener('DOMContentLoaded',init);